spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_test?serverTimezone=UTC&characterEncoding=UTF-8
    username: newuser
    password: 4585
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  application:
    name: boardTest

#logging:
 # level:
 #   org.hibernate.SQL: trace
 #   org.hibernate.orm.jdbc.bind: trace

#debug: true

